---
title: "Week_07_Map_In_Class"
author: Leah Barkai
date: today
format: html
editor: visual
---

## Load Libraries

```{r}
library(tidyverse)
library(here)
library(maps)
library(mapdata)
library(mapproj)

```

## Load in Data

```{r}
# Read in data on population in California by county
popdata<-read_csv(here("Week_07","Data","CApopdata.csv"))
#read in data on number of seastars at different field sites
stars<-read_csv(here("Week_07","Data","stars.csv"))
# get data for the entire world
world<-map_data("world")
head(world)
#for usa
usa<-map_data("usa")
#for italy
italy<-map_data("italy")
# get data for states
states<-map_data("state")
# get data for counties
counties<-map_data("county")

```

## Data Analysis

World map

```{r}
ggplot()+
  geom_polygon(data = world, aes(x = long, y = lat, group = group))

```

World map with lines are black

```{r}
ggplot()+
  geom_polygon(data = world, 
               aes(x = long, y = lat, group = group),
               color = "black")

```

World map with color

```{r}
ggplot()+
  geom_polygon(data = world, 
               aes(x = long, 
                   y = lat, 
                   group = group, 
                   fill = region),
               color = "black") +
  guides(fill = FALSE)

```

The earth isn't flat so adding the mercator

```{r}
ggplot()+
  geom_polygon(data = world, 
               aes(x = long, 
                   y = lat, 
                   group = group,
                   fill = region),
               color = "black")+
  theme_minimal()+
  guides(fill = FALSE)+
  theme(panel.background = element_rect(fill = "lightblue"))+
  coord_map(projection = "mercator",
            xlim = c(-180,180))

```

Doing a map of California

```{r}
# Use the states dataset
CA_data<-states %>%
  filter(region == "california")

ggplot()+
  geom_polygon(data = CA_data, 
               aes(x = long, 
                   y = lat, 
                   group = group,
                   fill = region),
               color = "black")



```

```{r}
# Look at the county data
head(counties)[1:3,] # only showing the first 3 rows for space
head(popdata)
CApop_county<-popdata %>%
  select("subregion" = County, Population)  %>% # rename the county col
  inner_join(counties) %>%
  filter(region == "california") # some counties have same names in other states
CApop_county<-popdata %>%
  select("subregion" = County, Population)  %>% # rename the county col
  inner_join(counties) %>%
  filter(region == "california") # some counties have same names in other states
## Joining with by = join_by(subregion)
head(CApop_county)
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),
             color = "black")+
  coord_map()+
  theme_void()

```

# **Map of CA population by county**

```{r}
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),  
             color = "black")+
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10")

```

```{r}
head(stars)

```

```{r}
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),  
             color = "black")+
  geom_point(data = stars, # add a point at all my sites
             aes(x = long,
                 y = lat))+
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10")

```

```{r}
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),  
             color = "black")+
  geom_point(data = stars, # add a point at all my sites 
             aes(x = long, 
                 y = lat,
                 size = star_no))+
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10")

```

```{r}
remotes::install_github("R-CoderDotCom/ggdogs@main")
library(ggdogs)
ggplot(mtcars) +
  geom_dog(aes(mpg, wt), dog = "pug", size = 5)

```
